### ISSUE TITLE
扫描aar问题

### ISSUE THREAD

**Issue by Harlber** [TokenYc/LintDemo#1]
- 翻了下源码，入口scope只有这几种生效
![截屏2021-11-22 下午10 56 32](https://user-images.githubusercontent.com/7955320/142883510-2ced0d21-15ce-4601-ba70-f261f58e584b.png)

- 这些scope，都是不包含aar的，很好奇你的aar扫描如何实现（除了手动解压添加）

**Comment by TokenYc** [comment]
![image](https://user-images.githubusercontent.com/11829523/143376776-b87c5848-321d-482d-8c71-36a73b7c55f5.png)
我的理解是：本质上，aar文件就是jar文件+一些资源文件
![image](https://user-images.githubusercontent.com/11829523/143376890-ce57f247-de76-4b98-bc35-997f7ffbfb11.png)
所以，可以扫描到。
@Harlber

**Comment by Harlber** [comment]
所以你博客中显示的一些扫描结果有部分是从aar中扫描出来的么

**Comment by TokenYc** [comment]
> 所以你博客中显示的一些扫描结果有部分是从aar中扫描出来的么

是的

**Comment by Harlber** [comment]
- 因为我多次执行，发现aar中扫描不到，跟了下其中的代码逻辑：
 
![截屏2021-11-25 下午9 59 29](https://user-images.githubusercontent.com/7955320/143456725-af2a37f7-8848-479a-bb2b-bb67174da25d.png)

其中`libraries`清一色全是jar
最终跟到了 `LintClient.kt`
![截屏2021-11-25 下午10 17 43](https://user-images.githubusercontent.com/7955320/143457477-cc257e42-4590-4b34-a561-b8d27054775f.png)
其中逻辑表明，lint会将项目中`libs`下的jar添加进去作为项目的java_libraries资源，`但其中并未看到任何关于aar的操作`，以上代码基于`com.android.tools.lint:lint-api:26.1.2`

**Comment by Harlber** [comment]
跑了下你这个项目，确实可行
